version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./www:/var/www
    networks:
      - symfony_app
    depends_on:
      - backend
      - symfony
    environment:
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./www:/var/www
    networks:
      - symfony_app

  symfony:
    ports:
      - 80:80
    build:
      context: ./symfony
      dockerfile: Dockerfile
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini:ro
      - ./www:/var/www/html
    networks:
      - symfony_app
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:          
      MYSQL_ROOT_PASSWORD: Foutaise.1
      MYSQL_DATABASE: api
      MYSQL_USER: doloresHaze
      MYSQL_PASSWORD: Foutaise.1    
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - symfony_app 

  # apache:
  #   image: php:8.1-apache
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./www:/var/www
  #   depends_on:
  #     - symfony
  #   networks:
  #     - symfony_app

volumes:
  symfony_app_var:
  symfony_app_vendor:
  db_app:

networks:
  symfony_app:
