# Dockerfile pour le backend MySQL
FROM mysql:8.0

# Variables d'environnement pour la configuration de MySQL
ENV MYSQL_DATABASE=api
ENV MYSQL_USER=doloresHaze
ENV MYSQL_PASSWORD=Foutaise.1
ENV MYSQL_ROOT_PASSWORD=Foutaise.1

# Copie des fichiers SQL initiaux
# COPY init.sql /docker-entrypoint-initdb.d/

# Exposition du port MySQL (par défaut : 3306)
EXPOSE 3308
